Run pep8 tests with python2
We currently can't install the requirements anymore on Python3 for the
pep8 check. It fails at

	Collecting MarkupSafe===1.0
	  Using cached MarkupSafe-1.0.tar.gz (14 kB)
		ERROR: Command errored out with exit status 1:
		 command: /oslo.vmware/.tox/pep8/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-vey_tk94/markupsafe/setup.py'"'"'; __file__='"'"'/tmp/pip-install-vey_tk94/markupsafe/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-hygl4fxr
			 cwd: /tmp/pip-install-vey_tk94/markupsafe/
		Complete output (5 lines):
		Traceback (most recent call last):
		  File "<string>", line 1, in <module>
		  File "/tmp/pip-install-vey_tk94/markupsafe/setup.py", line 6, in <module>
			from setuptools import setup, Extension, Feature
		ImportError: cannot import name 'Feature'
		----------------------------------------

Installing on Python2, which is also what we use this branch on, still
works, so we do the pep8 checks that way.

Change-Id: I599190772b806c9c938cee382ee494191812d9ea